const BUILD_LABEL = process.env.NEXT_PUBLIC_BUILD_LABEL ?? "dev";

interface Params {
  params: Promise<{ id: string }>;
}

async function getItem(id: string) {
  // Build B renames the route param key from 'id' to 'itemId' in the response.
  // The prefetched RSC payload from build A carries 'id'; build B's component
  // expects 'itemId' to render correctly. This is a contract drift on the
  // server response, the kind of failure that produces silent wrong-shape data.
  const data = {
    name: `Item ${id}`,
    description: `An interesting item with id ${id}, served from build ${BUILD_LABEL}.`,
    price: 49.99,
  };

  if (BUILD_LABEL === "B") {
    return { itemId: id, ...data, _shape: "v2-renamed" };
  }
  return { id, ...data, _shape: "v1-original" };
}

export default async function ItemPage({ params }: Params) {
  const { id } = await params;
  const item = await getItem(id);

  return (
    <>
      <h1>{item.name}</h1>
      <p style={{ color: "#666" }}>
        Identifier field: <code>{(item as any).id ?? (item as any).itemId}</code>
      </p>
      <p style={{ color: "#666" }}>
        Shape: <code>{item._shape}</code>
      </p>
      <p>{item.description}</p>
      <p>
        <strong>Price:</strong> ${item.price.toFixed(2)}
      </p>
      <p style={{ marginTop: "2rem", padding: "1rem", background: "#f6f8fa", borderRadius: 4 }}>
        <strong>Skew note:</strong> When this page is reached via a prefetched
        link from a stale items list, the RSC payload was generated by the OLD
        build (e.g. with field <code>id</code>) but the NEW build's component
        expects field <code>itemId</code>. Result: silent wrong-shape rendering,
        or a hydration mismatch error.
      </p>
    </>
  );
}
